language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "0.11"
  - "0.10"

matrix:
  include:
    # Create docker image on merge to develop
    - language: python
      python: "3.6"
      sudo: required
      dist: trusty
      services: [docker]
      env:
        - IMAGE_NAME=praekeltfoundation/go-jsbox-malaria24:develop
        - REGISTRY_USER=praekeltorgdeploy
        # REGISTRY_PASS
        - secure: "mM0uBezPjY+R1L0rliGrDeOgxu54qJKDMcNbxriJgmaQFik/XEcJvAeKNCfRyBVaXRZvugMBXw2SVrHg8WNZ5KXAM9nxcx1yF3YDmzeDPalYhwfQfMxhiI1UPqXGjcov7xIWvfBMJqPxT+r9Axv5DeLgAedS0QtS3R6ZfxNF8VRK7XIvzLBjJqMv9OEbpdeNIS2xO5Gt5F4z4+HhUAblsBMRdsErAyZ19qZ1PIH3p7QzVsJzn6wzVGtTkvCUIHQCm1yL01rpBX/dJ+hBiDttyrxb5HjDMOQmstQl1mQwBMMMLg85DJPvSYe9D83vw81KIa5K7kbJ7sxEqGoqee2X9R3Sj8H6SZnHlSALRALk0tK43t6NPY+wCOfdd1xnDquStwWGUkLL4daW1L3id50Uiq8oMGkNIUfekSx92UMM2so8B/v/QB3Mm67HCG+TkPE0QOWerOacYrsv6HJN2O+kK7Sc623PmdHpO8L9jzMCerzr+QjcHjMuvIW8PlzJCrZonqyu70SW21vhOZuHL7PdjtcuyAAGGUrPH9mieUs7/u5vh8mAO5hnhwAru1FGnr152mnird31Eaw6YNdzRvsPj1SQ4VR+skks1pl0I4A1eZsmQUm93pBhuOt8ip9k3am0hRGbxxcWWws9kG+PmpwQpkRl8GM/A+jj5EqmS+N545I="
      before_script:
        - docker pull "$IMAGE_NAME" || true
      script:
        - docker build --tag "$IMAGE_NAME" --cache-from "$IMAGE_NAME" .

      before_deploy:
        - pip install docker-ci-deploy==0.3.0
        - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
      deploy:
        provider: script
        script: dcd --version "$(git rev-parse --short HEAD)" --version-latest "$IMAGE_NAME"
        on:
          branch: develop
